name: Highlight new NPM Dependencies
description: Add a message in Pull Request with basic information when new dependencies are added
author: Damien Senger <hello@raccoon.studio>
branding:
  icon: plus-square
  color: gray-dark
inputs:
  token:
    description: Auth Token for the GitHub API
runs:
  using: node12
  main: dist/index.js
